In [1]:
import re

In [2]:
text = "This is a good day."

# Now, lets see if it's a good day or not:
if re.search("good", text): # the first parameter here is the pattern
    print("Wonderful!")
else:
    print("Alas :(")

Wonderful!


In [3]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

# This is a bit of a fabricated example, but lets split this on all instances of Amy
re.split("Amy", text)

['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is succesful.']

In [4]:
re.findall("Amy", text)

['Amy', 'Amy', 'Amy']

In [5]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

# Lets see if this begins with Amy
re.search("^Amy",text)

<re.Match object; span=(0, 3), match='Amy'>

In [7]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

# Lets see if this begins with Amy
if re.search("^Amy",text):
    print('Matched')
else:
    print('Not matched')

Matched


In [8]:
grades="ACAAAABCBCBAA"

# If we want to answer the question "How many B's were in the grade list?" we would just use B
re.findall("B",grades)

['B', 'B', 'B']

In [9]:
re.findall("[AB]",grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']

In [10]:
re.findall('[A][B-C]', grades)

['AC', 'AB']

In [11]:
re.findall('AB|AC', grades)

['AC', 'AB']

In [14]:
re.findall('[^A]', grades)

['C', 'B', 'C', 'B', 'C', 'B']

In [15]:
re.findall('^[^A]', grades)

[]

In [16]:
re.findall('A{2,10}', grades)

['AAAA', 'AA']

In [17]:
re.findall('A{1,1}A{1,1}', grades)

['AA', 'AA', 'AA']

In [19]:
re.findall('A{2,2}', grades)

['AA', 'AA', 'AA']

In [20]:
with open("datasets/ferpa.txt","r") as file:
    # we'll read that into a variable called wiki
    wiki=file.read()
# and lets print that variable out to the screen
wiki

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ferpa.txt'

In [21]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [22]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

In [24]:
import numpy as np
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [25]:
a1.shape

(4,)

In [26]:
a2.shape

(4, 1)

In [27]:
a3.shape

(1, 4)

In [28]:
a4.shape

(3,)

In [29]:
a5.shape

(4,)

In [30]:
a4.ndim()

TypeError: 'int' object is not callable

In [31]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [32]:
np.array([[1, 1, 1], [1, 1, 1]])

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
r = np.random.randn(6,6)
print(r)

[[ 0.01203018 -0.6418788   0.85989467  0.32451044  0.8418031  -0.25068239]
 [ 1.19631549 -1.41626081 -0.09709481 -0.03514506 -0.212586   -0.18387815]
 [-1.07015003  0.22088659 -0.28326476  1.52846436  0.73812514  1.50751282]
 [ 1.03772055 -1.77065319 -0.69352509  1.56640727 -1.54512309 -1.26341015]
 [ 0.67877918  0.12999902 -0.20878828  0.17444078 -1.34887631 -0.42463563]
 [-1.49739852  0.11433162  0.51704692 -1.00966772  0.44088454 -0.01041676]]


In [41]:
r[2:4, 2:4]

array([[-0.28326476,  1.52846436],
       [-0.69352509,  1.56640727]])

In [42]:
import re
s = 'ACBCAC'

In [44]:
re.findall('^AC',s)

['AC']

In [45]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

In [46]:
L

5

In [47]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

In [52]:
import re

pattern = '\(.\) '
print(len(re.findall(pattern,text)))

4


In [53]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

In [67]:
a = np.random.randn(20,20)

In [68]:
b = np.random.randn(20,20)

In [70]:
l2_dist(np.reshape(a,(20*20)), np.reshape(b,(20*20,1)))

583.0568253827387

In [72]:
l2_dist(a.T,b.T)

29.0253598815299

In [73]:
d = {'request': "djsfsdjfbj"}

In [89]:
lis= list(d.values())

In [77]:
l = [{'hi':'df', 'ji': 'ko'},{'ko':'nm'}]

In [78]:
l

[{'hi': 'df', 'ji': 'ko'}, {'ko': 'nm'}]

In [90]:
l[0]['requests']= lis[0]

In [91]:
l

[{'hi': 'df',
  'ji': 'ko',
  'req': "dict_values(['djsfsdjfbj'])",
  'requ': dict_values(['djsfsdjfbj']),
  'request': "dict_values(['djsfsdjfbj'])",
  'requests': 'djsfsdjfbj'},
 {'ko': 'nm'}]